version: "3.9"

services:

  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER: admin
      - POSTGRES_PASSWORD: password
      - POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"